export enum TypeServiceLVAO {
  achat_revente_particuliers = 'achat_revente_particuliers',
  achat_revente_professionnel = 'achat_revente_professionnel',
  relai_acteurs_et_evenements = 'relai_acteurs_et_evenements',
  atelier_pour_reparer_soi_meme = 'atelier_pour_reparer_soi_meme',
  depot_vente = 'depot_vente',
  don_particuliers = 'don_particuliers',
  echanges_particuliers = 'echanges_particuliers',
  espace_de_partage = 'espace_de_partage',
  localtion_particuliers = 'localtion_particuliers',
  location_professionnel = 'location_professionnel',
  partage_particuliers = 'partage_particuliers',
  pieces_detachees = 'pieces_detachees',
  recyclerie = 'recyclerie',
  service_de_reparation = 'service_de_reparation',
  structure_qui_sous_traite_la_reparation = 'structure_qui_sous_traite_la_reparation',
  structure_de_collecte = 'structure_de_collecte',
  tutoriels_et_diagnostics_en_ligne = 'tutoriels_et_diagnostics_en_ligne',
}
