import { Echelle } from '../aides/echelle';
import { TagUtilisateur } from '../scoring/tagUtilisateur';
import { Thematique } from '../thematique/thematique';
import { Categorie } from './categorie';
import { ContenuLocal } from './contenuLocal';
import { DifficultyLevel } from './difficultyLevel';
import { Source } from './source';

export class ArticleDefinition implements ContenuLocal {
  content_id: string;
  titre: string;
  soustitre: string;
  source: string;
  sources: Source[];
  contenu: string;
  image_url: string;
  partenaire_id: string;
  rubrique_ids: string[];
  rubrique_labels: string[];
  codes_postaux: string[];
  echelle: Echelle;
  duree: string;
  frequence: string;
  difficulty: DifficultyLevel;
  points: number;
  thematique_principale: Thematique;
  thematiques: Thematique[];
  tags_utilisateur: TagUtilisateur[];
  categorie: Categorie;
  mois: number[];
  include_codes_commune: string[];
  exclude_codes_commune: string[];
  codes_departement: string[];
  codes_region: string[];
  derniere_maj: Date;
  tags_a_inclure: string[];
  tags_a_exclure: string[];
  VISIBLE_PROD: boolean;
  codes_commune_from_partenaire: string[];
  codes_departement_from_partenaire: string[];
  codes_region_from_partenaire: string[];
}
