export enum ContentType {
  article = 'article',
  aide = 'aide',
  aides = 'aides',
  suivi_du_jour = 'suivi_du_jour',
  quizz = 'quizz',
  enchainement = 'enchainement',
  onboarding = 'onboarding',
  service = 'service',
  profile = 'profile',
  recommandations = 'recommandations',
  kyc = 'kyc',
  defi = 'defi',
  mosaic = 'mosaic',
}
