version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: 'daily'
    labels:
      - dependencies
    allow:
      - dependency-name: '@betagouv/aides-velo'
      - dependency-name: '@betagouv/publicodes-voiture'
      - dependency-name: '@incubateur-ademe/nosgestesclimat'
      - dependency-name: 'publicodes'
