export enum Tag_v2 {
  est_proprietaire = 'est_proprietaire',
  n_est_pas_proprietaire = 'n_est_pas_proprietaire',
  est_locataire = 'est_locataire',
  mange_de_la_viande = 'mange_de_la_viande',
  prend_l_avion = 'prend_l_avion',
  a_une_voiture = 'a_une_voiture',
  n_a_pas_de_voiture = 'n_a_pas_de_voiture',
  ne_prend_pas_avion = 'ne_prend_pas_avion',
  a_un_velo = 'a_un_velo',
  a_une_voiture_thermique = 'a_une_voiture_thermique',
  a_une_voiture_electrique = 'a_une_voiture_electrique',
  ne_mange_pas_de_viande_rouge = 'ne_mange_pas_de_viande_rouge',
  ne_mange_pas_de_viande = 'ne_mange_pas_de_viande',
  mange_de_saison = 'mange_de_saison',
  ne_mange_pas_de_saison = 'ne_mange_pas_de_saison',
  composte = 'composte',
  ne_composte_pas = 'ne_composte_pas',
  ne_mange_pas_local = 'ne_mange_pas_local',
  mange_local = 'mange_local',
  a_un_jardin = 'a_un_jardin',
  n_a_pas_de_jardin = 'n_a_pas_de_jardin',
  a_chauffage_elec = 'a_chauffage_elec',
  n_a_pas_chauffage_elec = 'n_a_pas_chauffage_elec',
  a_fait_travaux_recents = 'a_fait_travaux_recents',
  prend_soin_objets = 'prend_soin_objets',
  achete_peu_et_occasion = 'achete_peu_et_occasion',
  vit_en_appart = 'vit_en_appart',
  vit_en_maison = 'vit_en_maison',
  est_une_action_locale = 'est_une_action_locale',

  appetence_thematique_logement = 'appetence_thematique_logement',
  appetence_thematique_transport = 'appetence_thematique_transport',
  appetence_thematique_consommation = 'appetence_thematique_consommation',
  appetence_thematique_alimentation = 'appetence_thematique_alimentation',
}
