export enum Tag_v2 {
  est_proprietaire = 'est_proprietaire',
  n_est_pas_proprietaire = 'n_est_pas_proprietaire',
  est_locataire = 'est_locataire',
  mange_de_la_viande = 'mange_de_la_viande',
  prend_l_avion = 'prend_l_avion',
  a_une_voiture = 'a_une_voiture',
  n_a_pas_de_voiture = 'n_a_pas_de_voiture',
  ne_prend_pas_avion = 'ne_prend_pas_avion',
  a_un_velo = 'a_un_velo',
  a_une_voiture_thermique = 'a_une_voiture_thermique',
  a_une_voiture_electrique = 'a_une_voiture_electrique',
  ne_mange_pas_de_viande_rouge = 'ne_mange_pas_de_viande_rouge',
  ne_mange_pas_de_viande = 'ne_mange_pas_de_viande',
  mange_de_saison = 'mange_de_saison',
  ne_mange_pas_de_saison = 'ne_mange_pas_de_saison',
  composte = 'composte',
  ne_composte_pas = 'ne_composte_pas',
  ne_mange_pas_local = 'ne_mange_pas_local',
  mange_local = 'mange_local',
  a_un_jardin = 'a_un_jardin',
  n_a_pas_de_jardin = 'n_a_pas_de_jardin',
  a_chauffage_elec = 'a_chauffage_elec',
  n_a_pas_chauffage_elec = 'n_a_pas_chauffage_elec',
  a_fait_travaux_recents = 'a_fait_travaux_recents',
  prend_soin_objets = 'prend_soin_objets',
  achete_peu_et_occasion = 'achete_peu_et_occasion',
  vit_en_appart = 'vit_en_appart',
  vit_en_maison = 'vit_en_maison',
  est_un_contenu_local = 'est_un_contenu_local',

  appetence_thematique_logement = 'appetence_thematique_logement',
  appetence_thematique_transport = 'appetence_thematique_transport',
  appetence_thematique_consommation = 'appetence_thematique_consommation',
  appetence_thematique_alimentation = 'appetence_thematique_alimentation',

  habite_zone_peri_urbaine = 'habite_zone_peri_urbaine',
  habite_zone_urbaine = 'habite_zone_urbaine',
  habite_zone_rurale = 'habite_zone_rurale',

  contenu_important = 'contenu_important',
  match_aucun_autre_tag = 'match_aucun_autre_tag',

  risque_adresse_argile = 'risque_adresse_argile',
  risque_adresse_inondation = 'risque_adresse_inondation',
  risque_adresse_radon = 'risque_adresse_radon',
  risque_adresse_secheresse = 'risque_adresse_secheresse',
  risque_adresse_seisme = 'risque_adresse_seisme',
  risque_adresse_submersion = 'risque_adresse_submersion',
  risque_adresse_tempete = 'risque_adresse_tempete',
  risque_commune_catnat = 'risque_commune_catnat',
  risque_commune_argile = 'risque_commune_argile',
  risque_commune_inondation = 'risque_commune_inondation',

  recommandation_winter = 'recommandation_winter',
  habite_en_outre_mer = 'habite_en_outre_mer',
  habite_en_metropole = 'habite_en_metropole',

  ne_vit_pas_en_famille = 'ne_vit_pas_en_famille',
  vit_en_famille = 'vit_en_famille',
  // DEPRECATED: replaced by `vit_en_famille` in v25
  vie_en_famille = 'vie_en_famille',
}
