/**
 * NOTE: le mapping avec les valeur associées pour les réponses des KYCs à
 * choix, sont définies dans 'src/domain/kyc/publicodesMapping.ts' et permet
 * d'avoir un typechecking plus fort pour la manipulation des réponses KYC.
 */
export enum KYCID {
  _1 = '_1',
  _2 = '_2',
  _3 = '_3',
  _4 = '_4',
  _5 = '_5',
  KYC001 = 'KYC001', //Sur quels sujets souhaitez-vous en savoir plus concernant votre impact environnemental ?
  KYC002 = 'KYC002', //Quel(s) moyen(s)de transport excluez-vous pour vos trajets du quotidien (travail, courses…) ?
  KYC003 = 'KYC003', //Êtes-vous équipé(e) d’un vélo ?
  KYC004 = 'KYC004', //Comment trouvez-vous les pistes cyclables sur vos trajets du quotidien (trajet effectué plus de 2 fois par semaine)  ?
  KYC005 = 'KYC005', //Quelle est votre situation professionnelle ?
  KYC006 = 'KYC006', //Quel est l’âge de votre logement ?
  KYC007 = 'KYC007', // Quelle(s) boisson(s) chaude(s) consommez-vous quotidiennement ?
  KYC008 = 'KYC008', // Comment réalisez-vous vos trajet en voiture ?
  KYC009 = 'KYC009', // Comment réalisez-vous vos trajets en voiture ?
  KYC010 = 'KYC010', //Votre maison donne-t-elle accès à un jardin ?
  KYC011 = 'KYC011', //Effectuez-vous quotidiennement des trajets de moins de 10 min en voiture ?
  KYC012 = 'KYC012', //Effectuez-vous quotidiennement des trajets de moins de 10 min en voiture ?
  KYC013 = 'KYC013', //Qu'est-ce qui vous intéresse sur le sujet des transports ?
  KYC_menage = 'KYC_menage',
  KYC_changer_voiture = 'KYC_changer_voiture',
  KYC_conso_elec = 'KYC_conso_elec',
  KYC_temperature = 'KYC_temperature',
  KYC_logement_reno_second_oeuvre = 'KYC_logement_reno_second_oeuvre',
  KYC_logement_reno_isolation = 'KYC_logement_reno_isolation',
  KYC_logement_reno_chauffage = 'KYC_logement_reno_chauffage',
  KYC_logement_reno_extension = 'KYC_logement_reno_extension',
  KYC_2roue_km = 'KYC_2roue_km',
  KYC_2roue_motorisation_type = 'KYC_2roue_motorisation_type',
  KYC_achat_chaussure = 'KYC_achat_chaussure',
  KYC_achat_chemise = 'KYC_achat_chemise',
  KYC_achat_gros_article = 'KYC_achat_gros_article',
  KYC_achat_manteau = 'KYC_achat_manteau',
  KYC_achat_pantalon = 'KYC_achat_pantalon',
  KYC_achat_petit_article = 'KYC_achat_petit_article',
  KYC_achat_pull = 'KYC_achat_pull',
  KYC_achat_robe = 'KYC_achat_robe',
  KYC_achat_short = 'KYC_achat_short',
  KYC_achat_sweat = 'KYC_achat_sweat',
  KYC_achat_tshirt = 'KYC_achat_tshirt',
  KYC_alimentation_regime = 'KYC_alimentation_regime',
  KYC_petitdej = 'KYC_petitdej',
  KYC_bilan = 'KYC_bilan',
  KYC_chauffage_bois = 'KYC_chauffage_bois',
  KYC_chauffage_elec = 'KYC_chauffage_elec',
  KYC_chauffage_fioul = 'KYC_chauffage_fioul',
  KYC_chauffage_gaz = 'KYC_chauffage_gaz',
  KYC_chauffage = 'KYC_chauffage',
  KYC_chauffage_pompe_chaleur = 'KYC_chauffage_pompe_chaleur',
  KYC_chauffage_reseau = 'KYC_chauffage_reseau',
  KYC_DPE = 'KYC_DPE',
  KYC_logement_age = 'KYC_logement_age',
  KYC_logement_exterieur_salon_bois = 'KYC_logement_exterieur_salon_bois',
  KYC_logement_exterieur_salon_resine_metal = 'KYC_logement_exterieur_salon_resine_metal',
  KYC_logement_exterieur_tondeuse_elec = 'KYC_logement_exterieur_tondeuse_elec',
  KYC_logement_exterieur_tondeuse_therm = 'KYC_logement_exterieur_tondeuse_therm',
  KYC_logement_exterieur_bbq_elec_gaz = 'KYC_logement_exterieur_bbq_elec_gaz',
  KYC_logement_exterieur_bbq_charbon = 'KYC_logement_exterieur_bbq_charbon',
  KYC_consommation_logement_vacances_hotel = 'KYC_consommation_logement_vacances_hotel',
  KYC_consommation_logement_vacances_camping = 'KYC_consommation_logement_vacances_camping',
  KYC_consommation_logement_vacances_auberge_jeunesse = 'KYC_consommation_logement_vacances_auberge_jeunesse',
  KYC_consommation_logement_vacances_locations = 'KYC_consommation_logement_vacances_locations',
  KYC_consommation_logement_vacance_famille = 'KYC_consommation_logement_vacance_famille',
  KYC_consommation_logement_vacances_echange = 'KYC_consommation_logement_vacances_echange',
  KYC_consommation_logement_vacances_secondaire = 'KYC_consommation_logement_vacances_secondaire',
  KYC_electro_robot_cuisine = 'KYC_electro_robot_cuisine',
  KYC_electro_aspirateur = 'KYC_electro_aspirateur',
  KYC_electro_cafetiere = 'KYC_electro_cafetiere',
  KYC_electro_bouilloire = 'KYC_electro_bouilloire',
  KYC_electro_hotte = 'KYC_electro_hotte',
  KYC_electro_plaques = 'KYC_electro_plaques',
  KYC_electro_micro_onde = 'KYC_electro_micro_onde',
  KYC_electro_four = 'KYC_electro_four',
  KYC_electro_lave_vaiselle = 'KYC_electro_lave_vaiselle',
  KYC_electro_seche_linge = 'KYC_electro_seche_linge',
  KYC_electro_lave_linge = 'KYC_electro_lave_linge',
  KYC_consommation_relation_objets = 'KYC_consommation_relation_objets',
  KYC_consommation_type_consommateur = 'KYC_consommation_type_consommateur',
  KYC_local_frequence = 'KYC_local_frequence',
  KYC_alimentation_litres_alcool = 'KYC_alimentation_litres_alcool',
  KYC_gaspillage_alimentaire_frequence = 'KYC_gaspillage_alimentaire_frequence',
  KYC_alimentation_compostage = 'KYC_alimentation_compostage',
  KYC_alimentation_reduc_gaspi_alim = 'KYC_alimentation_reduc_gaspi_alim',
  KYC_alimentation_stoppub = 'KYC_alimentation_stoppub',
  KYC_alimentation_achat_vrac = 'KYC_alimentation_achat_vrac',
  KYC_consommation_petit_chien = 'KYC_consommation_petit_chien',
  KYC_consommation_moyen_chien = 'KYC_consommation_moyen_chien',
  KYC_consommation_grand_chien = 'KYC_consommation_grand_chien',
  KYC_consommation_chat = 'KYC_consommation_chat',
  KYC_appareil_telephone = 'KYC_appareil_telephone',
  KYC_appareil_television = 'KYC_appareil_television',
  KYC_appareil_ordi_portable = 'KYC_appareil_ordi_portable',
  KYC_appareil_ordi_fixe = 'KYC_appareil_ordi_fixe',
  KYC_appareil_tablette = 'KYC_appareil_tablette',
  KYC_appareil_enceinte_bluetooth = 'KYC_appareil_enceinte_bluetooth',
  KYC_appareil_console_salon = 'KYC_appareil_console_salon',
  KYC_appareil_console_portable = 'KYC_appareil_console_portable',
  KYC_appareil_imprimante_nbr = 'KYC_appareil_imprimante_nbr',
  KYC_meuble_armoire = 'KYC_meuble_armoire',
  KYC_meuble_canape = 'KYC_meuble_canape',
  KYC_meuble_chaise = 'KYC_meuble_chaise',
  KYC_meuble_grand_meuble = 'KYC_meuble_grand_meuble',
  KYC_meuble_lit = 'KYC_meuble_lit',
  KYC_meuble_matelas = 'KYC_meuble_matelas',
  KYC_meuble_petit_meuble = 'KYC_meuble_petit_meuble',
  KYC_meuble_table = 'KYC_meuble_table',
  KYC_nbr_plats_poisson_blanc = 'KYC_nbr_plats_poisson_blanc',
  KYC_nbr_plats_poisson_gras = 'KYC_nbr_plats_poisson_gras',
  KYC_nbr_plats_vegetaliens = 'KYC_nbr_plats_vegetaliens',
  KYC_nbr_plats_vegetariens = 'KYC_nbr_plats_vegetariens',
  KYC_nbr_plats_viande_blanche = 'KYC_nbr_plats_viande_blanche',
  KYC_nbr_plats_viande_rouge = 'KYC_nbr_plats_viande_rouge',
  KYC_photovoltaiques = 'KYC_photovoltaiques',
  KYC_preference = 'KYC_preference',
  KYC_proprietaire = 'KYC_proprietaire',
  KYC_jardin = 'KYC_jardin',
  KYC_saison_frequence = 'KYC_saison_frequence',
  KYC_superficie = 'KYC_superficie',
  KYC_transport_2roues_usager = 'KYC_transport_2roues_usager',
  KYC_transport_avion_3_annees = 'KYC_transport_avion_3_annees',
  KYC_transport_heures_avion_court = 'KYC_transport_heures_avion_court',
  KYC_transport_heures_avion_long = 'KYC_transport_heures_avion_long',
  KYC_transport_heures_avion_moyen = 'KYC_transport_heures_avion_moyen',
  /** Utilisez-vous majoritairement la même voiture pour vous déplacer ? */
  KYC_transport_type_utilisateur = 'KYC_transport_type_utilisateur',
  /** Quelle distance parcourez-vous à l'année en voiture ? (en km) */
  KYC_transport_voiture_km = 'KYC_transport_voiture_km',
  /** Quel est le gabarit de la voiture ? */
  KYC_transport_voiture_gabarit = 'KYC_transport_voiture_gabarit',
  /** Quel type de voiture utilisez vous ? */
  KYC_transport_voiture_motorisation = 'KYC_transport_voiture_motorisation',
  KYC_transport_vae_possede = 'KYC_transport_vae_possede',
  /** Quel type de carburant votre voiture consomme-t-elle ? */
  KYC_transport_voiture_thermique_carburant = 'KYC_transport_voiture_thermique_carburant',
  KYC_transport_voiture_nbr_voyageurs = 'KYC_transport_voiture_nbr_voyageurs',
  KYC_type_logement = 'KYC_type_logement',
  /** Est-ce une voiture d'occasion ? */
  KYC_transport_voiture_occasion = 'KYC_transport_voiture_occasion',
  /** Combien de temps envisagez-vous de la garder au total ? */
  KYC_transport_voiture_duree_detention = 'KYC_transport_voiture_duree_detention',
  /** Quelle est son année de fabrication ? */
  KYC_transport_voiture_annee_fabrication = 'KYC_transport_voiture_annee_fabrication',
  KYC_transport_voiture_prix_achat = 'KYC_transport_voiture_prix_achat',
  /** Quelle est sa consommation moyenne de carburant ? */
  KYC_transport_voiture_thermique_consomation_carburant = 'KYC_transport_voiture_thermique_consomation_carburant',
  KYC_transport_voiture_thermique_prix_carburant = 'KYC_transport_voiture_thermique_prix_carburant',
  KYC_transport_voiture_electrique_consommation = 'KYC_transport_voiture_electrique_consommation',
  KYC_transport_voiture_electrique_prix_kwh = 'KYC_transport_voiture_electrique_prix_kwh',
  KYC_transport_voiture_couts_entretien = 'KYC_transport_voiture_couts_entretien',
  KYC_transport_voiture_couts_assurance = 'KYC_transport_voiture_couts_assurance',
  KYC_transport_voiture_couts_stationnement = 'KYC_transport_voiture_couts_stationnement',
  KYC_transport_voiture_couts_peage = 'KYC_transport_voiture_couts_peage',
  KYC_possede_voiture_oui_non = 'KYC_possede_voiture_oui_non',
  KYC_electro_refrigerateur = 'KYC_electro_refrigerateur',
  KYC_electro_petit_refrigerateur = 'KYC_electro_petit_refrigerateur',
  KYC_electro_congelateur = 'KYC_electro_congelateur',
  KYC_loisir_piscine_type = 'KYC_loisir_piscine_type',
  KYC_raison_achat_vetements = 'KYC_raison_achat_vetements',
}
