export enum KYCMosaicID {
  TEST_MOSAIC_ID = 'TEST_MOSAIC_ID',
  MOSAIC_CHAUFFAGE = 'MOSAIC_CHAUFFAGE',
  MOSAIC_RENO = 'MOSAIC_RENO',
  MOSAIC_EXTERIEUR = 'MOSAIC_EXTERIEUR',
  MOSAIC_LOGEMENT_VACANCES = 'MOSAIC_LOGEMENT_VACANCES',
  MOSAIC_ELECTROMENAGER = 'MOSAIC_ELECTROMENAGER',
  MOSAIC_REDUCTION_DECHETS = 'MOSAIC_REDUCTION_DECHETS',
  MOSAIC_ANIMAUX = 'MOSAIC_ANIMAUX',
  MOSAIC_APPAREIL_NUM = 'MOSAIC_APPAREIL_NUM',
}
