export enum TagExcluant {
  ne_prend_pas_avion = 'ne_prend_pas_avion',
  a_un_velo = 'a_un_velo',
  na_pas_de_voiture = 'na_pas_de_voiture',
  a_une_voiture_electrique = 'a_une_voiture_electrique',
  mange_pas_de_viande = 'mange_pas_de_viande',
  mange_pas_de_viande_rouge = 'mange_pas_de_viande_rouge',
  mange_de_saison = 'mange_de_saison',
  mange_local = 'mange_local',
  composte = 'composte',
  vit_en_appart = 'vit_en_appart',
  est_locataire = 'est_locataire',
  na_pas_de_jardin = 'na_pas_de_jardin',
  a_chauffage_elec = 'a_chauffage_elec',
  a_fait_travaux_recents = 'a_fait_travaux_recents',
  prend_soin_objets = 'prend_soin_objets',
  achete_peu_et_occasion = 'achete_peu_et_occasion',
}
