export enum CodeBesoin {
  acheter_velo = 'acheter_velo',
  emprunter_velo = 'emprunter_velo',
  louer_velo = 'louer_velo',
  louer_vehicule_elec = 'louer_vehicule_elec',
  reduc_transports_communs = 'reduc_transports_communs',
  reno_logement = 'reno_logement',
  broyer_vege = 'broyer_vege',
  rehab_assain_non_collectif = 'rehab_assain_non_collectif',
  planter_arbre = 'planter_arbre',
  recup_eau_pluie = 'recup_eau_pluie',
  change_sys_chauffage = 'change_sys_chauffage',
  reparer_objet_elec = 'reparer_objet_elec',
  reparer_vet_chauss = 'reparer_vet_chauss',
  composter = 'composter',
  emprunter_gob_reu = 'emprunter_gob_reu',
  couches_lavables = 'couches_lavables',
  collecte_dechets_verts = 'collecte_dechets_verts',
  energies_renouvelables = 'energies_renouvelables',
  covoiturer = 'covoiturer',
  acheter_voiture_electrique = 'acheter_voiture_electrique',
  vegetaliser_logement = 'vegetaliser_logement',
  reparer_velo = 'reparer_velo',
  trier_dechets = 'trier_dechets',
  reduire_dechets = 'reduire_dechets',
  economiser_eau = 'economiser_eau',
  agir_pour_environnement = 'agir_pour_environnement',
  planter_haie = 'planter_haie',
  sport_en_nature = 'sport_en_nature',
  protections_hygieniques_lavables = 'protections_hygieniques_lavables',
  gerer_conso_energie = 'gerer_conso_energie',
}

export type Besoin = CodeBesoin | string;
export const Besoin = { ...CodeBesoin };
