export enum Besoin {
  acheter_velo = 'acheter_velo',
  emprunter_velo = 'emprunter_velo',
  louer_velo = 'louer_velo',
  louer_vehicule_elec = 'louer_vehicule_elec',
  reduc_transports_communs = 'reduc_transports_communs',
  reno_logement = 'reno_logement',
  broyer_vege = 'broyer_vege',
  rehab_assain_non_collectif = 'rehab_assain_non_collectif',
  planter_arbre = 'planter_arbre',
  recup_eau_pluie = 'recup_eau_pluie',
  change_sys_chauffage = 'change_sys_chauffage',
  reparer_objet_elec = 'reparer_objet_elec',
  reparer_vet_chauss = 'reparer_vet_chauss',
  composter = 'composter',
  emprunter_gob_reu = 'emprunter_gob_reu',
  couches_lavables = 'couches_lavables',
}
