// FIXME: shouldn't be an enum a they are abitrary and can change over time
export enum Besoin {
  acheter_velo = 'acheter_velo',
  emprunter_velo = 'emprunter_velo',
  louer_velo = 'louer_velo',
  louer_vehicule_elec = 'louer_vehicule_elec',
  reduc_transports_communs = 'reduc_transports_communs',
  reno_logement = 'reno_logement',
  broyer_vege = 'broyer_vege',
  rehab_assain_non_collectif = 'rehab_assain_non_collectif',
  planter_arbre = 'planter_arbre',
  recup_eau_pluie = 'recup_eau_pluie',
  change_sys_chauffage = 'change_sys_chauffage',
  reparer_objet_elec = 'reparer_objet_elec',
  reparer_vet_chauss = 'reparer_vet_chauss',
  composter = 'composter',
  emprunter_gob_reu = 'emprunter_gob_reu',
  couches_lavables = 'couches_lavables',
  collecte_dechets_verts = 'collecte_dechets_verts',
  energies_renouvelables = 'energies_renouvelables',
  covoiturer = 'covoiturer',
  acheter_voiture_électrique = 'acheter_voiture_électrique',
  vegetaliser_logement = 'vegetaliser_logement',
  reparer_velo = 'reparer_velo',
  trier_dechets = 'trier_dechets',
  reduire_dechets = 'reduire_dechets',
  'Économiser-eau' = 'Économiser-eau',
  "Agir pour l'environnement" = "Agir pour l'environnement",
  'Planter une haie' = 'Planter une haie',
  'Pratiquer une activité sportive dans la nature' = 'Pratiquer une activité sportive dans la nature',
  'Utiliser des protections hygiéniques lavables' = 'Utiliser des protections hygiéniques lavables',
  "Gérer sa consommation d'énergie" = "Gérer sa consommation d'énergie",
}
