export enum CMSModel {
  quizz = 'quizz',
  article = 'article',
  aide = 'aide',
  faq = 'faq',
  text = 'text',
  conformite = 'conformite',
  thematique = 'thematique',
  univers = 'univers',
  'thematique-univers' = 'thematique-univers',
  partenaire = 'partenaire',
  kyc = 'kyc',
  mission = 'mission',
  action = 'action',
  'action-classique' = 'action-classique',
  'action-simulateur' = 'action-simulateur',
  'action-bilan' = 'action-bilan',
  'action-quizz' = 'action-quizz',
  unkown = 'unkown',
}
