export enum CMSModel {
  quizz = 'quizz',
  article = 'article',
  aide = 'aide',
  conformite = 'conformite',
  thematique = 'thematique',
  univers = 'univers',
  'thematique-univers' = 'thematique-univers',
  defi = 'defi',
  partenaire = 'partenaire',
  kyc = 'kyc',
  mission = 'mission',
  action = 'action',
  unkown = 'unkown',
}
