name: Build and run tests

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    services:
      db-tests:
        image: postgres:14
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: tests

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test:unit

      - name: Integration tests
        run: |
          npm run db:update
          npm run test:int
        env:
          DATABASE_URL: 'postgresql://prisma:prisma@localhost:5432/tests'
          DATABASE_STATS_URL: 'postgresql://prisma:prisma@localhost:5432/stats'
          INTERNAL_TOKEN_SECRET: '123456789012345678901234567890'
          MINIATURES_URL: 'http://localhost:3000'
